image: node:16.15

definitions:
  steps:
    - step: &test-build
        name: Test & Build
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run build:prod
        artifacts:
          - dist/**
    - step: &deploy-staging
        name: Deploy
        script:
          - scp -r dist/ ubuntu@$SERVER_IP_STAGING:~/software
          - scp package.json ubuntu@$SERVER_IP_STAGING:~/software
          - scp package-lock.json ubuntu@$SERVER_IP_STAGING:~/software
          - scp pm2-deploy.sh ubuntu@$SERVER_IP_STAGING:~/software
          - ssh ubuntu@$SERVER_IP_STAGING 'chmod +x ~/software/pm2-deploy.sh && ~/software/pm2-deploy.sh'
    - step: &deploy
        name: Deploy
        script:
          - scp -r dist/ ubuntu@$SERVER_IP:~/software
          - scp package.json ubuntu@$SERVER_IP:~/software
          - scp package-lock.json ubuntu@$SERVER_IP:~/software
          - scp pm2-deploy.sh ubuntu@$SERVER_IP:~/software
          - scp ormconfig.ts ubuntu@$SERVER_IP:~/software
          - scp -r migrations/ ubuntu@$SERVER_IP:~/software
          - ssh ubuntu@$SERVER_IP 'chmod +x ~/software/pm2-deploy.sh && ~/software/pm2-deploy.sh'

pipelines:
  pull-requests:
    '**':
      - step: *test-build
  branches:
    staging:
      - step: *test-build
      - step: *deploy-staging
    master:
      - step: *test-build
      - step: *deploy