export const ERROR_CODES = {
  INSUFFICIENT_INFORMATION: 'INSUFFICIENT_INFORMATION',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
